### ISSUE TITLE
Archived means no 1.20 and I’m depressed

### ISSUE THREAD

**Issue by Rebel459** [Blumbo/ArmorTweaks#1]
If you ever get the time, just know that I (and the few hundred people that enjoy one of my modpacks) would greatly appreciate getting this mod back for 1.20 to rework the armor system.

**Comment by not-coded** [comment]
I am working on porting the 1.19.x version to the 1.20.x as I'm writing this, as I need it for another project.

**Comment by Rebel459** [comment]
That’s great! Really appreciate that you’re doing this, my modpack will greatly appreciate it :)

**Comment by not-coded** [comment]
> That’s great! Really appreciate that you’re doing this, my modpack will greatly appreciate it :)

i have released the 1.20 version to [my fork](<https://github.com/not-coded/ArmorTweaks/releases>).

**Comment by Blumbo** [comment]
accepted notcoded's pull request

**Comment by Rebel459** [comment]
Could the pull request be uploaded to modrinth by any chance?

**Comment by Blumbo** [comment]
There https://modrinth.com/mod/armortweaks/version/2.0.2-1.20
